CREATE TABLE IF NOT EXISTS `DIM_TIME_DELEGATE`
(
	`TIME_ID` VARCHAR(10) default '' NOT NULL,
	`MONTH_ID` INTEGER default 0 NOT NULL,
	`QTR_ID` INTEGER default 0 NOT NULL,
	`YEAR_ID` INTEGER default 0 NOT NULL,
	`MONTH_NAME` VARCHAR(3) default '0' NOT NULL,
	`MONTH_DESC` VARCHAR(15) default '' NOT NULL,
	`QTR_NAME` VARCHAR(4) default '' NOT NULL,
	`QTR_DESC` VARCHAR(15) default '' NOT NULL,
	PRIMARY KEY (`TIME_ID`)
)Type=MyISAM  DEFAULT CHARSET='utf8' COMMENT='The application';

TRUNCATE DIM_TIME_DELEGATE;

insert into DIM_TIME_DELEGATE
SELECT
  DISTINCT SUBSTRING(DEL_DELEGATE_DATE,1,10),
  MONTH(DEL_DELEGATE_DATE),
  QUARTER(DEL_DELEGATE_DATE),
  YEAR(DEL_DELEGATE_DATE),
  DATE_FORMAT ( DEL_DELEGATE_DATE, '%b'),
  DATE_FORMAT ( DEL_DELEGATE_DATE, '%M %Y'),
  CONCAT( 'QTR', QUARTER(DEL_DELEGATE_DATE) ),
  CONCAT( 'Quarter ', QUARTER(DEL_DELEGATE_DATE), ' ', YEAR(DEL_DELEGATE_DATE) )
FROM APP_CACHE_VIEW
WHERE SUBSTRING(DEL_DELEGATE_DATE,1,10) != 'NULL';
