<?php
G::LoadClass("plugin");

class aquitaineProjectPlugin extends PMPlugin
{
  private $dashletsUids;
  
  public function aquitaineProjectPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "aquitaineProject Plugin";
    $this->sDescription  = "Autogenerated plugin for class aquitaineProject";
    $this->sPluginFolder = "aquitaineProject";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 2.3;//may 21
    //$this->iPMVersion    = 2425;
    //$this->aWorkspaces   = null;
    $this->aWorkspaces = array("aquitaine");
    
    
    $this->dashletsUids = array(
      array("DAS_UID" => "587604557515a877d2f0826017094445",
            "DAS_CLASS" => "dashletaquitaineProject",
            "DAS_TITLE" => "Dashlet aquitaineProject",
            "DAS_DESCRIPTION" => "Dashlet aquitaineProject",
            "DAS_VERSION" => "1.0",
            "DAS_CREATE_DATE" => date("Y-m-d"),
            "DAS_UPDATE_DATE" => date("Y-m-d"))
    );
    
    
    return $res;
  }

  public function setup()
  {
    $this->setCompanyLogo("/plugin/aquitaineProject/aquitaineProject.png");
    $this->registerPmFunction();
    

    // End Find the Url inside to Cases Steps
    
    $this->registerDashlets();
  }

  public function install()
  {
    /*$RBAC = RBAC::getSingleton() ;
    $RBAC->initRBAC();
    $roleData = array();
    $roleData["ROL_UID"] = G::GenerateUniqueId();
    $roleData["ROL_PARENT"] = "";
    $roleData["ROL_SYSTEM"] = "00000000000000000000000000000002";
    $roleData["ROL_CODE"] = "PROCESSMAKER_AQUITAINEPROJECT";
    $roleData["ROL_CREATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_UPDATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_STATUS"] = "1";
    $RBAC->createRole($roleData);
    $RBAC->createPermision("PM_AQUITAINEPROJECT");*/
  }
  
  public function enable()
  {
    $this->dashletInsert();
  }

  public function disable()
  {
    $this->dashletDelete();
  }
  
  public function dashletInsert()
  {
    require_once ("classes/model/Dashlet.php");
    
    $connection = Propel::getConnection(DashletPeer::DATABASE_NAME);
    
    foreach ($this->dashletsUids as $dashletData) {
      $dashlet = new Dashlet();
      
      if (is_null($dashlet->load($dashletData["DAS_UID"]))) {
        $dashlet->fromArray($dashletData, BasePeer::TYPE_FIELDNAME);
        $connection->begin();
        $dashlet->save();
        $connection->commit();
      }
    }
  }
  
  public function dashletDelete()
  {
    require_once ("classes/model/Dashlet.php");
    
    foreach ($this->dashletsUids as $dashletData) {
      $criteria = new Criteria("workflow");
      $criteria->add(DashletPeer::DAS_UID, $dashletData["DAS_UID"]);
      DashletPeer::doDelete($criteria);
    }
  }
}

if(class_exists("headPublisher"))
{
    $oHeadPublisher =& headPublisher::getSingleton();
    $oHeadPublisher->addScriptFile("/plugin/aquitaineProject/resize_iframe.js",1);
    $oHeadPublisher->addScriptFile("/plugin/aquitaineProject/convergence.js",1);
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("aquitaineProject", __FILE__);
