<?php
G::LoadClass("plugin");

class convergenceListPlugin extends PMPlugin
{
  private $dashletsUids;
  
  public function convergenceListPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "convergenceList Plugin";
    $this->sDescription  = "Autogenerated plugin for class convergenceList";
    $this->sPluginFolder = "convergenceList";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 3.7; //Jul 29
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces   = array("convergence","workflow", "fred","aquitaine","rnpc");    
    
    
    $this->dashletsUids = array(
      array("DAS_UID" => "461829358515a87991f7f18056659552",
            "DAS_CLASS" => "dashletconvergenceList",
            "DAS_TITLE" => "Dashlet convergenceList",
            "DAS_DESCRIPTION" => "Dashlet convergenceList",
            "DAS_VERSION" => "1.0",
            "DAS_CREATE_DATE" => date("Y-m-d"),
            "DAS_UPDATE_DATE" => date("Y-m-d"))
    );
    
    
    return $res;
  }

  public function setup()
  {    
    $this->registerMenu( "cases", "newOptionCases.php");
    $this->registerPmFunction();
    $this->copy( 'services' . PATH_SEP . 'cronCreateCases.php', PATH_CORE . 'bin' . PATH_SEP . 'plugins' . PATH_SEP . 'cronCreateCases.php', false, true ); 
  }

  public function install()
  {
    /*$RBAC = RBAC::getSingleton() ;
    $RBAC->initRBAC();
    $roleData = array();
    $roleData["ROL_UID"] = G::GenerateUniqueId();
    $roleData["ROL_PARENT"] = "";
    $roleData["ROL_SYSTEM"] = "00000000000000000000000000000002";
    $roleData["ROL_CODE"] = "PROCESSMAKER_CONVERGENCELIST";
    $roleData["ROL_CREATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_UPDATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_STATUS"] = "1";
    $RBAC->createRole($roleData);
    $RBAC->createPermision("PM_CONVERGENCELIST");*/
    $this->copy( 'services' . PATH_SEP . 'cronCreateCases.php', PATH_CORE . 'bin' . PATH_SEP . 'plugins' . PATH_SEP . 'cronCreateCases.php', false, true ); 
  }
  
  public function enable()
  {
    $this->dashletInsert();
  }

  public function disable()
  {
    $this->dashletDelete();
  }
  
  public function dashletInsert()
  {
    require_once ("classes/model/Dashlet.php");
    
    $connection = Propel::getConnection(DashletPeer::DATABASE_NAME);
    
    foreach ($this->dashletsUids as $dashletData) {
      $dashlet = new Dashlet();
      
      if (is_null($dashlet->load($dashletData["DAS_UID"]))) {
        $dashlet->fromArray($dashletData, BasePeer::TYPE_FIELDNAME);
        $connection->begin();
        $dashlet->save();
        $connection->commit();
      }
    }
  }
  
  public function dashletDelete()
  {
    require_once ("classes/model/Dashlet.php");
    
    foreach ($this->dashletsUids as $dashletData) {
      $criteria = new Criteria("workflow");
      $criteria->add(DashletPeer::DAS_UID, $dashletData["DAS_UID"]);
      DashletPeer::doDelete($criteria);
    }
  }
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("convergenceList", __FILE__);
