<?php
G::LoadClass("plugin");

class idfTranSportPlugin extends PMPlugin
{
  
  
  public function idfTranSportPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "idfTranSport Plugin";
    $this->sDescription  = "Autogenerated plugin for class idfTranSport";
    $this->sPluginFolder = "idfTranSport";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->setCompanyLogo("/plugin/idfTranSport/idfTranSport.png");
    $this->registerPmFunction();
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("idfTranSport", __FILE__);
