<?php
define('LimousinPort','8084');
G::LoadClass("plugin");

class limousinProjectPlugin extends PMPlugin
{
  
  
  public function limousinProjectPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "limousinProject Plugin";
    $this->sDescription  = "Autogenerated plugin for class limousinProject";
    $this->sPluginFolder = "limousinProject";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->setCompanyLogo("/plugin/limousinProject/limousinProject.png");
    $this->registerPmFunction();
    $this->redirectLogin("PROCESSMAKER_LIMOUSINPROJECT", "users/users_List");
    
    
  }

  public function install()
  {
    $RBAC = RBAC::getSingleton() ;
    $RBAC->initRBAC();
    $roleData = array();
    $roleData["ROL_UID"] = G::GenerateUniqueId();
    $roleData["ROL_PARENT"] = "";
    $roleData["ROL_SYSTEM"] = "00000000000000000000000000000002";
    $roleData["ROL_CODE"] = "PROCESSMAKER_LIMOUSINPROJECT";
    $roleData["ROL_CREATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_UPDATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_STATUS"] = "1";
    $RBAC->createRole($roleData);
    $RBAC->createPermision("PM_LIMOUSINPROJECT");
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("limousinProject", __FILE__);
