<?php
G::LoadClass("plugin");

class NordPDCPlugin extends PMPlugin
{
  
  
  public function NordPDCPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "NordPDC Plugin";
    $this->sDescription  = "Autogenerated plugin for class NordPDC";
    $this->sPluginFolder = "NordPDC";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    //$this->aWorkspaces   = null;
    $this->aWorkspaces = array("CheqLivreApp");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->setCompanyLogo("/plugin/NordPDC/NordPDC.png");
    $this->registerPmFunction();
    
    
  }

  public function install()
  {
    $RBAC = RBAC::getSingleton() ;
    $RBAC->initRBAC();
    $roleData = array();
    $roleData["ROL_UID"] = G::GenerateUniqueId();
    $roleData["ROL_PARENT"] = "";
    $roleData["ROL_SYSTEM"] = "00000000000000000000000000000002";
    $roleData["ROL_CODE"] = "PROCESSMAKER_NORDPDC";
    $roleData["ROL_CREATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_UPDATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_STATUS"] = "1";
    $RBAC->createRole($roleData);
    $RBAC->createPermision("PM_NORDPDC");
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("NordPDC", __FILE__);
