<?php
G::LoadClass("plugin");

class obladyConvergencePlugin extends PMPlugin
{
  
  
  public function obladyConvergencePlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "obladyConvergence Plugin";
    $this->sDescription  = "Autogenerated plugin for class obladyConvergence";
    $this->sPluginFolder = "obladyConvergence";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerPmFunction();
    
    // Find the Url inside to Cases Steps
    $path = $_SERVER['REQUEST_URI'];
    $find = 'cases/cases_Step';
    $pos = strpos($path, $find);
    if ($pos !== false)
    {
      $oHeadPublisher =& headPublisher::getSingleton();
      $oHeadPublisher->addScriptFile("/plugin/obladyConvergence/workspaceRemoveSteps.js",1);
    }
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

if(class_exists("headPublisher"))
{
    $oHeadPublisher =& headPublisher::getSingleton();
    $oHeadPublisher->addScriptFile("/plugin/obladyConvergence/resize_iframe.js",1);
    $oHeadPublisher->addScriptFile("/plugin/obladyConvergence/convergence.js",1);
    $oHeadPublisher->addScriptFile("/plugin/obladyConvergence/json2.js",1);
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("obladyConvergence", __FILE__);
