<?php
G::LoadClass("plugin");

class phpExcelLibraryProjectPlugin extends PMPlugin
{
  
  
  public function phpExcelLibraryProjectPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "phpExcelLibraryProject Plugin";
    $this->sDescription  = "Autogenerated plugin for class phpExcelLibraryProject";
    $this->sPluginFolder = "phpExcelLibraryProject";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerPmFunction();
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("phpExcelLibraryProject", __FILE__);
