<?php
G::LoadClass("plugin");

class pmReplicatorPlugin extends PMPlugin
{
  
  
  public function pmReplicatorPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "pmReplicator Plugin";
    $this->sDescription  = "Autogenerated plugin for class pmReplicator";
    $this->sPluginFolder = "pmReplicator";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerMenu( 'setup', 'menu.php');
    $oHeadPublisher =& headPublisher::getSingleton();
    $oHeadPublisher->addScriptFile("/plugin/pmReplicator/javaScripts/tclAuxiliary.js",1);
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("pmReplicator", __FILE__);
