<?php
G::LoadClass("plugin");

class pmWorkspaceManagementPlugin extends PMPlugin
{
  
  
  public function pmWorkspaceManagementPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "pmWorkspaceManagement Plugin";
    $this->sDescription  = "Autogenerated plugin for class pmWorkspaceManagement";
    $this->sPluginFolder = "pmWorkspaceManagement";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1.1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerMenu( 'setup', 'menu.php');
    require_once(PATH_PLUGINS.'pmWorkspaceManagement'.PATH_SEP.'classes'.PATH_SEP.'class.multitenantInstaller.php');
		multitenantInstaller::install();
    
  }

  public function install()
  {
  		
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("pmWorkspaceManagement", __FILE__);
