CREATE TRIGGER APP_DELEGATION_UPDATE
ON APP_DELEGATION
AFTER UPDATE
AS
BEGIN

  SET NOCOUNT ON;

  DECLARE @DEFAULT_LANG VARCHAR(2);
  SET @DEFAULT_LANG = 'en';

	DECLARE @APP_UID VARCHAR(50);
	DECLARE @DEL_INDEX INT;
	DECLARE @DEL_PREVIOUS INT;
	DECLARE @PRO_UID VARCHAR(50);
	DECLARE @TAS_UID VARCHAR(50);
	DECLARE @USR_UID VARCHAR(50);
	DECLARE @DEL_TYPE VARCHAR;
	DECLARE @DEL_THREAD INT;
	DECLARE @DEL_THREAD_STATUS VARCHAR(50);
	DECLARE @DEL_PRIORITY VARCHAR(50);
	DECLARE @DEL_DELEGATE_DATE CHAR(19);
	DECLARE @DEL_INIT_DATE CHAR(19);
	DECLARE @DEL_TASK_DUE_DATE CHAR(19);
	DECLARE @DEL_FINISH_DATE CHAR(19);
	DECLARE @DEL_DURATION FLOAT;
	DECLARE @DEL_QUEUE_DURATION FLOAT;
	DECLARE @DEL_DELAY_DURATION FLOAT;
	DECLARE @DEL_STARTED tinyint;
	DECLARE @DEL_FINISHED tinyint;
	DECLARE @DEL_DELAYED tinyint;
	DECLARE @DEL_DATA VARCHAR(max);
	DECLARE @APP_OVERDUE_PERCENTAGE FLOAT;
	DECLARE @APP_NUMBER INT; 
	DECLARE @APP_STATUS VARCHAR(50);
	DECLARE @APP_CREATE_DATE CHAR(19);
	DECLARE @APP_TITLE NVARCHAR(255);
	DECLARE @PRO_TITLE NVARCHAR(255);
	DECLARE @TAS_TITLE NVARCHAR(255);
	DECLARE @APP_CURRENT_USER NVARCHAR(255);
  DECLARE @APP_DEL_PREVIOUS_USER NVARCHAR(255);
  DECLARE @PREVIOUS_USR_UID VARCHAR(50);
  DECLARE @APP_THREAD_STATUS VARCHAR(50);
  
  DECLARE updateCursor CURSOR  FOR 
    SELECT APP_UID,
           DEL_INDEX, 
           DEL_PREVIOUS, 
           PRO_UID, 
           TAS_UID, 
           USR_UID, 
           DEL_TYPE, 
           DEL_THREAD, 
           DEL_THREAD_STATUS, 
           DEL_PRIORITY, 
           DEL_DELEGATE_DATE, 
           DEL_INIT_DATE, 
           DEL_TASK_DUE_DATE, 
           DEL_FINISH_DATE, 
           DEL_DURATION, 
           DEL_QUEUE_DURATION, 
           DEL_DELAY_DURATION, 
           DEL_STARTED, 
           DEL_FINISHED, 
           DEL_DELAYED, 
           DEL_DATA, 
           APP_OVERDUE_PERCENTAGE 
    FROM INSERTED;
  OPEN updateCursor;
  
  FETCH NEXT FROM updateCursor INTO 
             @APP_UID,
             @DEL_INDEX, 
             @DEL_PREVIOUS, 
             @PRO_UID, 
             @TAS_UID, 
             @USR_UID, 
             @DEL_TYPE, 
             @DEL_THREAD, 
             @DEL_THREAD_STATUS, 
             @DEL_PRIORITY, 
             @DEL_DELEGATE_DATE, 
             @DEL_INIT_DATE, 
             @DEL_TASK_DUE_DATE, 
             @DEL_FINISH_DATE, 
             @DEL_DURATION, 
             @DEL_QUEUE_DURATION, 
             @DEL_DELAY_DURATION, 
             @DEL_STARTED, 
             @DEL_FINISHED, 
             @DEL_DELAYED, 
             @DEL_DATA, 
             @APP_OVERDUE_PERCENTAGE ;

  WHILE @@FETCH_STATUS = 0
  BEGIN
    SET @APP_NUMBER = 0;
    SET @APP_STATUS = '';
    SET @APP_CREATE_DATE = '';
    SET @APP_TITLE = '';
    SET @PRO_TITLE = '';
    SET @TAS_TITLE = '';
    SET @APP_CURRENT_USER = '';
    SET @APP_DEL_PREVIOUS_USER = '';
    SET @PREVIOUS_USR_UID = '';
    SET @APP_THREAD_STATUS = 'OPEN';
    
    SELECT @APP_NUMBER = APP_NUMBER, @APP_STATUS = APP_STATUS, @APP_CREATE_DATE = APP_CREATE_DATE 
      from APPLICATION WHERE APP_UID = @APP_UID;

    SELECT @APP_TITLE = CON_VALUE FROM CONTENT WHERE CON_ID = @APP_UID AND CON_CATEGORY = 'APP_TITLE' and CON_LANG = @DEFAULT_LANG;
    SELECT @PRO_TITLE = CON_VALUE FROM CONTENT WHERE CON_ID = @PRO_UID AND CON_CATEGORY = 'PRO_TITLE' and CON_LANG = @DEFAULT_LANG;
    SELECT @TAS_TITLE = CON_VALUE FROM CONTENT WHERE CON_ID = @TAS_UID AND CON_CATEGORY = 'TAS_TITLE' and CON_LANG = @DEFAULT_LANG;

    SELECT @APP_CURRENT_USER = USR_LASTNAME + ' ' + USR_FIRSTNAME FROM USERS WHERE USR_UID = @USR_UID;
    IF ( @DEL_PREVIOUS > 0 ) 
    BEGIN
      SELECT @PREVIOUS_USR_UID = USR_UID FROM APP_DELEGATION WHERE APP_UID = @APP_UID AND DEL_INDEX = @DEL_PREVIOUS;
      SELECT @APP_DEL_PREVIOUS_USER = USR_LASTNAME + ' ' + USR_FIRSTNAME FROM USERS WHERE USR_UID = @PREVIOUS_USR_UID;
    END;
    
    SELECT @APP_THREAD_STATUS = APP_THREAD_STATUS FROM APP_THREAD WHERE APP_UID = @APP_UID AND DEL_INDEX = @DEL_INDEX;

    UPDATE APP_CACHE_VIEW
    SET
      APP_NUMBER            =   @APP_NUMBER,
      APP_STATUS            =   @APP_STATUS,
      USR_UID               =   @USR_UID,
      PREVIOUS_USR_UID      =   @PREVIOUS_USR_UID,
      TAS_UID               =   @TAS_UID,
      PRO_UID               =   @PRO_UID,
      DEL_DELEGATE_DATE     =   @DEL_DELEGATE_DATE,
      DEL_INIT_DATE         =   @DEL_INIT_DATE,
      DEL_TASK_DUE_DATE     =   @DEL_TASK_DUE_DATE,
      DEL_FINISH_DATE       =   @DEL_FINISH_DATE,
      DEL_THREAD_STATUS     =   @DEL_THREAD_STATUS,
      APP_THREAD_STATUS     =   @APP_THREAD_STATUS,
      APP_TITLE             =   @APP_TITLE,
      APP_PRO_TITLE         =   @PRO_TITLE,
      APP_TAS_TITLE         =   @TAS_TITLE,
      APP_CURRENT_USER      =   @APP_CURRENT_USER,
      APP_DEL_PREVIOUS_USER =   @APP_DEL_PREVIOUS_USER,
      DEL_PRIORITY          =   @DEL_PRIORITY,
      DEL_DURATION          =   @DEL_DURATION,
      DEL_QUEUE_DURATION    =   @DEL_QUEUE_DURATION,
      DEL_DELAY_DURATION    =   @DEL_DELAY_DURATION,
      DEL_STARTED           =   @DEL_STARTED,
      DEL_FINISHED          =   @DEL_FINISHED,
      DEL_DELAYED           =   @DEL_DELAYED,
      APP_FINISH_DATE       =   NULL,
      APP_UPDATE_DATE       =   CONVERT(CHAR(19),GETDATE(),120),
      APP_OVERDUE_PERCENTAGE =  @APP_OVERDUE_PERCENTAGE
    WHERE
      APP_UID = @APP_UID
      AND DEL_INDEX = @DEL_INDEX;

    FETCH NEXT FROM updateCursor INTO 
               @APP_UID,
               @DEL_INDEX, 
               @DEL_PREVIOUS, 
               @PRO_UID, 
               @TAS_UID, 
               @USR_UID, 
               @DEL_TYPE, 
               @DEL_THREAD, 
               @DEL_THREAD_STATUS, 
               @DEL_PRIORITY, 
               @DEL_DELEGATE_DATE, 
               @DEL_INIT_DATE, 
               @DEL_TASK_DUE_DATE, 
               @DEL_FINISH_DATE, 
               @DEL_DURATION, 
               @DEL_QUEUE_DURATION, 
               @DEL_DELAY_DURATION, 
               @DEL_STARTED, 
               @DEL_FINISHED, 
               @DEL_DELAYED, 
               @DEL_DATA, 
               @APP_OVERDUE_PERCENTAGE ;
  END 
  CLOSE updateCursor;
  DEALLOCATE updateCursor;
END

