<?php
G::LoadClass("plugin");

class obladyConvergencePlugin extends PMPlugin
{
  
  
  public function obladyConvergencePlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "obladyConvergence Plugin";
    $this->sDescription  = "Autogenerated plugin for class obladyConvergence";
    $this->sPluginFolder = "obladyConvergence";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerPmFunction();
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("obladyConvergence", __FILE__);
